/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import data.RouteJDBC;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Route;
import models.User;

/**
 *
 * @author michael
 */
public class JDAddRoute extends javax.swing.JDialog {

    private JDUserPanel userPanel;
    
    /**
     * Creates new form JDAddRoute
     */
    public JDAddRoute(java.awt.Frame parent, boolean modal, JDUserPanel userPanel) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.userPanel = userPanel;
        this.jLMsg.setText("Add a route, " + this.userPanel.getUser().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTStartingLocation = new javax.swing.JTextField();
        jTFinalLocation = new javax.swing.JTextField();
        jTDistance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBAddRoute = new javax.swing.JButton();
        jLBack = new javax.swing.JLabel();
        jLMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ADD ROUTE");

        jBAddRoute.setText("Add route");
        jBAddRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAddRouteMouseClicked(evt);
            }
        });

        jLBack.setText("Back");
        jLBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackMouseClicked(evt);
            }
        });

        jLMsg.setText("Add a route, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jBAddRoute))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMsg)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTDistance, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jTStartingLocation))
                                .addGap(29, 29, 29)
                                .addComponent(jTFinalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLMsg)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTStartingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFinalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jTDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jBAddRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBack)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAddRouteMouseClicked
        String startingLocation = jTStartingLocation.getText();
        String finalLocation = jTFinalLocation.getText();
        double distance = Double.parseDouble(jTDistance.getText());
        
        Route route = new Route(this.userPanel.getUser(),
                startingLocation, finalLocation, distance);
        RouteJDBC routeJDBC = new RouteJDBC();
        
        try {
            routeJDBC.insert(route);
            JOptionPane.showMessageDialog(this, "Ruta creada con éxito");
            this.clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error creando la ruta");
        }
    }//GEN-LAST:event_jBAddRouteMouseClicked

    private void jLBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackMouseClicked
        this.clear();
        this.setVisible(false);
        this.userPanel.loadRoutes();
        this.userPanel.setVisible(true);
    }//GEN-LAST:event_jLBackMouseClicked

    private void clear () {
        jTStartingLocation.setText("");
        jTFinalLocation.setText("");
        jTDistance.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddRoute;
    private javax.swing.JLabel jLBack;
    private javax.swing.JLabel jLMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTDistance;
    private javax.swing.JTextField jTFinalLocation;
    private javax.swing.JTextField jTStartingLocation;
    // End of variables declaration//GEN-END:variables
}
