/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import data.NoveltyJDBC;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.ExceptionHandler;
import models.Novelty;
import models.Route;

/**
 *
 * @author michael
 */
public class JDNovelty extends javax.swing.JDialog {

    private Route route;    
    
    /**
     * Creates new form JDNovelty
     */
    public JDNovelty(java.awt.Frame parent, boolean modal ,Route route) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);        
        this.route = route;
        this.loadTypes();
        this.jLRoute.setText(String.format("End the route with id: %d, started in: %s at %s",
                this.route.getId(), this.route.getStartingLocation(),
                this.route.getStart()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCBType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jBtnAddNovelty = new javax.swing.JButton();
        jLBack = new javax.swing.JLabel();
        jLRoute = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 104, 123));

        jCBType.setBackground(new java.awt.Color(152, 237, 237));

        jTADescription.setBackground(new java.awt.Color(152, 237, 237));
        jTADescription.setColumns(20);
        jTADescription.setRows(5);
        jScrollPane1.setViewportView(jTADescription);

        jLabel3.setForeground(null);
        jLabel3.setText("NOVELTY");

        jBtnAddNovelty.setBackground(new java.awt.Color(34, 182, 75));
        jBtnAddNovelty.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAddNovelty.setText("Add novelty");
        jBtnAddNovelty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAddNoveltyMouseClicked(evt);
            }
        });

        jLBack.setForeground(null);
        jLBack.setText("Back");
        jLBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBackMouseClicked(evt);
            }
        });

        jLRoute.setForeground(null);
        jLRoute.setText("Route: ");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 2, 12)); // NOI18N
        jLabel7.setForeground(null);
        jLabel7.setText("Type");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 2, 12)); // NOI18N
        jLabel8.setForeground(null);
        jLabel8.setText("Description");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 350, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBtnAddNovelty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(310, 310, 310))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel3))
                    .addComponent(jLRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(jLRoute)
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jBtnAddNovelty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLBack)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTypes () {
        Novelty.Type[] types =  Novelty.Type.values();
        for (Novelty.Type t : types)
            jCBType.addItem(t.toString());
    }

    private void jBtnAddNoveltyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAddNoveltyMouseClicked
        addNovelty();
    }//GEN-LAST:event_jBtnAddNoveltyMouseClicked

    private void jLBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBackMouseClicked
        this.end();
    }//GEN-LAST:event_jLBackMouseClicked

    private void end () {        
        this.clear();
        this.dispose();
    }
    
    private void clear () {
        this.jCBType.setSelectedIndex(0);
        this.jTADescription.setText("");
    }
    
    private void addNovelty () {
        String description = jTADescription.getText();
        String type = jCBType.getSelectedItem().toString();
        Novelty novelty = new Novelty(this.route, type, description);
        NoveltyJDBC noveltyJDBC = new NoveltyJDBC();
        
        try {
            noveltyJDBC.insert(novelty);
            JOptionPane.showMessageDialog(this, "Se ha agregado la descripción");
            this.clear();
        } catch (SQLException ex) {
            ExceptionHandler.showErrorMsg(this, ex);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddNovelty;
    private javax.swing.JComboBox<String> jCBType;
    private javax.swing.JLabel jLBack;
    private javax.swing.JLabel jLRoute;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescription;
    // End of variables declaration//GEN-END:variables
}
